global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'resume-jd-matcher'
    static_configs:
      - targets: ['host.docker.internal:5000']
    metrics_path: '/metrics' 